# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-25 01:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dinner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=6)),
                ('unit', models.CharField(choices=[('', ''), ('oz', 'oz'), ('tablespoon', 'tablespoon'), ('teaspoon', 'teaspoon'), ('cups', 'cups'), ('clove', 'clove'), ('grams', 'grams'), ('thumb', 'thumb')], max_length=100)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient', to='dinner.Ingredient')),
            ],
        ),
    ]
