# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-25 01:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dinner', '0002_ingredientquantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='dish',
            name='ingredients',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='dinner.IngredientQuantity'),
            preserve_default=False,
        ),
    ]
