# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-25 01:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dinner', '0003_auto_20171025_0138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='ingredientquantity',
            name='dishes',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='dinner.Dish'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredientquantity',
            name='unit',
            field=models.CharField(choices=[('count', 'count'), ('oz', 'oz'), ('tablespoon', 'tablespoon'), ('teaspoon', 'teaspoon'), ('cups', 'cups'), ('clove', 'clove'), ('grams', 'grams'), ('thumb', 'thumb')], max_length=100),
        ),
    ]
